// @author Dmitry Patsura <talk@dmtry.me> https://github.com/ovr
// @flow

export const APP_PROFILE_SUCCESS = 'APP_PROFILE_SUCCESS'
export const APP_ORGANIZATIONS_SUCCESS = 'APP_ORGANIZATIONS_SUCCESS'
export const APP_LOGOUT_SUCCESS = 'APP_LOGOUT_SUCCESS'

export const SIDEMENU_OPEN = 'SIDEMENU_OPEN'
export const SIDEMENU_CLOSE = 'SIDEMENU_CLOSE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_2FA_REQUIRED = 'LOGIN_REQUEST_2FA_REQUIRED'

export const ACCOUNT_FEED_CHANGE_LOGIN = 'ACCOUNT_FEED_CHANGE_LOGIN'

export const ACCOUNT_FEED_REQUEST = 'ACCOUNT_FEED_REQUEST'
export const ACCOUNT_FEED_SUCCESS = 'ACCOUNT_FEED_SUCCESS'
export const ACCOUNT_FEED_FAIL = 'ACCOUNT_FEED_FAIL'

export const ACCOUNT_FEED_INFINITY_REQUEST = 'ACCOUNT_FEED_INFINITY_REQUEST'
export const ACCOUNT_FEED_INFINITY_SUCCESS = 'ACCOUNT_FEED_INFINITY_SUCCESS'
export const ACCOUNT_FEED_INFINITY_FAIL = 'ACCOUNT_FEED_INFINITY_FAIL'

export const ACCOUNT_ISSUES_REQUEST = 'ACCOUNT_ISSUES_REQUEST'
export const ACCOUNT_ISSUES_SUCCESS = 'ACCOUNT_ISSUES_SUCCESS'
export const ACCOUNT_ISSUES_FAIL = 'ACCOUNT_ISSUES_FAIL'

export const ACCOUNT_ISSUES_MORE_REQUEST = 'ACCOUNT_ISSUES_MORE_REQUEST'
export const ACCOUNT_ISSUES_MORE_SUCCESS = 'ACCOUNT_ISSUES_MORE_SUCCESS'
export const ACCOUNT_ISSUES_MORE_FAIL = 'ACCOUNT_ISSUES_MORE_FAIL'

export const ACCOUNT_PULL_REQUESTS_REQUEST = 'ACCOUNT_PULL_REQUESTS_REQUEST'
export const ACCOUNT_PULL_REQUESTS_SUCCESS = 'ACCOUNT_PULL_REQUESTS_SUCCESS'
export const ACCOUNT_PULL_REQUESTS_FAIL = 'ACCOUNT_PULL_REQUESTS_FAIL'

export const ACCOUNT_PULL_REQUESTS_MORE_REQUEST = 'ACCOUNT_PULL_REQUESTS_MORE_REQUEST'
export const ACCOUNT_PULL_REQUESTS_MORE_SUCCESS = 'ACCOUNT_PULL_REQUESTS_MORE_SUCCESS'
export const ACCOUNT_PULL_REQUESTS_MORE_FAIL = 'ACCOUNT_PULL_REQUESTS_MORE_FAIL'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_REQUEST_FAIL = 'PROFILE_REQUEST_FAIL'
export const PROFILE_REQUEST_SUCCESS = 'PROFILE_REQUEST_SUCCESS'

export const PROFILE_ORGANIZATIONS_REQUEST = 'PROFILE_ORGANIZATIONS_REQUEST'
export const PROFILE_ORGANIZATIONS_REQUEST_FAIL = 'PROFILE_ORGANIZATIONS_REQUEST_FAIL'
export const PROFILE_ORGANIZATIONS_REQUEST_SUCCESS = 'PROFILE_ORGANIZATIONS_REQUEST_SUCCESS'

export const REPOSITORY_REQUEST = 'REPOSITORY_REQUEST'
export const REPOSITORY_REQUEST_FAIL = 'REPOSITORY_REQUEST_FAIL'
export const REPOSITORY_REQUEST_SUCCESS = 'REPOSITORY_REQUEST_SUCCESS'

export const PROFILE_REPOSITORIES_REQUEST = 'PROFILE_REPOSITORIES_REQUEST'
export const PROFILE_REPOSITORIES_REQUEST_FAIL = 'PROFILE_REPOSITORIES_REQUEST_FAIL'
export const PROFILE_REPOSITORIES_REQUEST_SUCCESS = 'PROFILE_REPOSITORIES_REQUEST_SUCCESS'

export const PROFILE_REPOSITORIES_MORE_REQUEST = 'PROFILE_REPOSITORIES_MORE_REQUEST'
export const PROFILE_REPOSITORIES_MORE_REQUEST_FAIL = 'PROFILE_REPOSITORIES_MORE_REQUEST_FAIL'
export const PROFILE_REPOSITORIES_MORE_REQUEST_SUCCESS = 'PROFILE_REPOSITORIES_MORE_REQUEST_SUCCESS'

export const NAVIGATION_SET_TITLE = 'NAVIGATION_SET_TITLE'
export const NAVIGATION_HOME = 'NAVIGATION_HOME'
export const NAVIGATION_LOGIN = 'NAVIGATION_LOGIN'

export const ACCOUNT_ISSUES_LIMIT = 30
export const ACCOUNT_FEED_LIMIT = 30
export const ACCOUNT_PULL_REQUESTS_LIMIT = 30
