
fastlane_version "2.53.1"

default_platform :ios

platform :ios do
    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
        gym(scheme: "ghubber", include_bitcode: true) # Build your app - more options available
        testflight
    end
end

